develop
goslammu/datakeeper pull request #1
Opened 2023-03-16 21:45 UTC by goslammu

2023-03-20 18:48 UTC, lostsequence requested changes

2023-03-20 18:48 UTC, lostsequence commented on internal/client/session.go
> +	slf.dataPoints.Clear()
с синхронизацией не очень понятно.
если пользователь в офлайне добавил данные, то актуальные данные будут потеряны (так как сервере еще не обновились)

2023-03-20 18:48 UTC, lostsequence commented on internal/server/config.go
> +	flag.StringVar(&slf.UserStoragePath, "u", slf.UserStoragePath, "user storage file path")
зачастую сервер конфигурят с помощью переменных окружения, можно добавить к флагам

2023-03-20 18:48 UTC, lostsequence commented on internal/objects/userstorage/userstorage.go
> +// NotifyOnlineUser notofies user's sessions for syncronization.
typo: notofies -> notifies

2023-03-20 18:48 UTC, lostsequence commented on internal/server/server.go
> +
не используй пустой контекст, сделай с таймаутом

2023-03-20 18:48 UTC, lostsequence commented on internal/objects/storage/storage.go
> +	defer slf.mu.Unlock()
если с приложением работает много юзеров, то в случае с общим локом все будут ждать друг друга
в таких случаях можно использовать именованные мьютексы, например для конкретного юзера

2023-03-20 18:48 UTC, lostsequence commented on internal/server/handlers.go
> +
необходимо добавить тесты

2023-03-20 18:50 UTC, lostsequence commented on internal/server/handlers.go
> +	if err := slf.users.NotifyOnlineUser(userName); err != nil {
насколько я понял, на любую команду всегда полная синхронизация
можно было бы сделать на add не полную синхронизацию, а только того элемента, который добавили ?

2023-03-20 19:58 UTC, goslammu commented on cmd/datakeeperclient/main.go
> +	config.SetByExternal()
Исправлено!

2023-03-20 19:59 UTC, goslammu commented on internal/client/commands.go
> +	}
Исправлено! Оставил только инициализацию пустой мапы.

2023-03-20 20:00 UTC, goslammu commented on internal/client/handlers.go
> +	newDatapoint, err := d.New(cmd[2], cmd[3], cmd[4:])
Исправлено!

2023-03-20 20:02 UTC, goslammu commented on internal/client/commands.go
> +		return currentSession.sendCommand(cmd)
Если находимся онлайн, то сохраняем сразу на сервер, после чего приходит запрос на синхронизацию :)
Предполагал так: если находимся онлайн, то все возможные действия делаем сразу на сервере и ждём синхронизации.

2023-03-20 20:19 UTC, goslammu commented on internal/client/session.go
> +	slf.dataPoints.Clear()
Если мы дошли до этого места в методе, то клиент уже отправил свои данные на сервер, ответив на первичный пустой запрос синхронизации (первый if). Здесь же мы уже разбираем синхронизированные данные :)

2023-03-20 20:26 UTC, goslammu commented on internal/server/config.go
> +	flag.StringVar(&slf.UserStoragePath, "u", slf.UserStoragePath, "user storage file path")
Добавлено!

2023-03-20 20:31 UTC, goslammu commented on internal/server/server.go
> +
Исправлено!

2023-03-20 20:39 UTC, goslammu commented on internal/server/server.go
> +
Исправлено!

2023-03-20 20:54 UTC, goslammu commented on cmd/datakeeperclient/main.go
> +		if err := c.Shutdown(); err != nil {
Добавлено! И в сервер тоже.

2023-03-20 20:58 UTC, goslammu commented on internal/client/client.go
> +func (slf *client) Shutdown() error {
Добавлено!

2023-03-20 21:22 UTC, goslammu commented on internal/client/handlers.go
> +// handlerAdd deletes datapoint both on server and in local storage. Command syntax: "delete %datapoint name%".
Исправлено!

2023-03-20 21:23 UTC, goslammu commented on internal/objects/userstorage/userstorage.go
> +// NotifyOnlineUser notofies user's sessions for syncronization.
Исправлено :)

2023-03-20 21:23 UTC, goslammu commented on internal/objects/storage/storage.go
> +	defer slf.mu.Unlock()
Приму к сведению, спасибо! Если успею, попробую реализовать...

2023-03-22 09:13 UTC, goslammu commented on internal/client/process.go
> +	case _CMD_DEL: // delete %datapoint name%
Удаление оффлайн добавлено, сама логика удаления поправлена!

2023-03-22 20:56 UTC, goslammu commented on internal/server/handlers.go
> +	if err := slf.users.NotifyOnlineUser(userName); err != nil {
Приму как улучшение на будущее!

2023-03-22 21:06 UTC, goslammu commented on internal/server/handlers.go
> +
Добавлены!

2023-03-23 19:49 UTC, lostsequence commented on internal/client/handlers_test.go
> +		err := c.commandAdd(context.Background(), cmd, testSession)
много еще где используется пустой контекст

2023-03-23 19:52 UTC, lostsequence commented on internal/client/client.go
> +			log.Println(err)
логи лучше писать более информативные, добавлять контекст, по ошибке не всегда непонятно что к чему

2023-03-23 19:58 UTC, lostsequence commented on internal/client/commands.go
> +	slf.currentUser = &userData{
понял, когда следующий юзер заходит, то локально его данные с сервера записываются. То есть для нового логина полная синхронизация.

2023-03-23 20:00 UTC, lostsequence commented on internal/client/commands.go
> +		return currentSession.sendCommand(cmd)
хорошо, идею понял )

2023-03-23 20:13 UTC, lostsequence commented on internal/client/handlers.go
> +	}
лучше использовать tls для передачи данных вроде пароля )

2023-03-23 20:17 UTC, lostsequence commented on internal/client/handlers_test.go
> +func Test_Handlers(t *testing.T) {
постарайся в будущем наращивать покрытие тестами ) 100% я конечно нигде не встречал, но процентов 70-80% лучше иметь )

2023-03-24 04:48 UTC, merged